
package jp.rough_diamond.commons.util.mule.transformer.test.stub.sampleservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import jp.rough_diamond.commons.util.mule.transformer.test.stub.sampleservice.SampleServicePortType;

/**
 * This class was generated by Apache CXF 2.0.7
 * Sun Sep 21 18:05:24 JST 2008
 * Generated source version: 2.0.7
 * 
 */

@WebServiceClient(name = "SampleService", 
                  wsdlLocation = "file:/D:/products/isken/account/workspace/Sample/etc/wsdl/SampleService.wsdl",
                  targetNamespace = "http://sample.rough_diamond.jp/") 
public class SampleService extends Service {

    public final static URL WSDL_LOCATION;
    public final static QName SERVICE = new QName("http://sample.rough_diamond.jp/", "SampleService");
    public final static QName SampleServicePort = new QName("http://sample.rough_diamond.jp/", "SampleServicePort");
    static {
        URL url = null;
        try {
            url = new URL("file:/D:/products/isken/account/workspace/Sample/etc/wsdl/SampleService.wsdl");
        } catch (MalformedURLException e) {
            System.err.println("Can not initialize the default wsdl from file:/D:/products/isken/account/workspace/Sample/etc/wsdl/SampleService.wsdl");
            // e.printStackTrace();
        }
        WSDL_LOCATION = url;
    }

    public SampleService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public SampleService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SampleService() {
        super(WSDL_LOCATION, SERVICE);
    }

    /**
     * 
     * @return
     *     returns SampleServicePort
     */
    @WebEndpoint(name = "SampleServicePort")
    public SampleServicePortType getSampleServicePort() {
        return super.getPort(SampleServicePort, SampleServicePortType.class);
    }

}
