
package jp.rough_diamond.commons.util.mule.transformer.test.stub.sampleservice;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.0.7
 * Sun Sep 21 18:05:24 JST 2008
 * Generated source version: 2.0.7
 * 
 */

public final class SampleServicePortType_SampleServicePort_Client {

    private static final QName SERVICE_NAME = new QName("http://sample.rough_diamond.jp/", "SampleService");

    private SampleServicePortType_SampleServicePort_Client() {
    }

    public static void main(String args[]) throws Exception {
        URL wsdlURL = SampleService.WSDL_LOCATION;
        if (args.length > 0) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        SampleService ss = new SampleService(wsdlURL, SERVICE_NAME);
        SampleServicePortType port = ss.getSampleServicePort();  
        
        {
        System.out.println("Invoking doIt...");
        jp.rough_diamond.commons.util.mule.transformer.test.stub.sampleservice.ParentBean _doIt_arg0 = null;
        port.doIt(_doIt_arg0);


        }

        System.exit(0);
    }

}
