package jp.rough_diamond.commons.util.mule.transformer.test.stub.sampleservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.1.2
 * Wed May 13 14:36:27 JST 2009
 * Generated source version: 2.1.2
 * 
 */
 
@WebService(targetNamespace = "http://sample.rough_diamond.jp/", name = "SampleServicePortType")
@XmlSeeAlso({ObjectFactory.class})
public interface SampleServicePortType {

    @RequestWrapper(localName = "doIt", targetNamespace = "http://sample.rough_diamond.jp/", className = "jp.rough_diamond.commons.util.mule.transformer.test.stub.sampleservice.DoIt")
    @ResponseWrapper(localName = "doItResponse", targetNamespace = "http://sample.rough_diamond.jp/", className = "jp.rough_diamond.commons.util.mule.transformer.test.stub.sampleservice.DoItResponse")
    @WebMethod
    public void doIt(
        @WebParam(name = "arg0", targetNamespace = "http://sample.rough_diamond.jp/")
        jp.rough_diamond.commons.util.mule.transformer.test.stub.sampleservice.ParentBean arg0
    );
}
